### ISSUE TITLE
カードレイアウトが変わるときに画像の角丸の位置が変わっていない

### ISSUE THREAD

**Issue by eai04191** [shikorism/tissue#140]
PCで見るときは画像が左にあるので左上と左下を丸めればいいが、幅が狭くなると画像が上に来るので角丸は左上と右上になるべき。

![image](https://user-images.githubusercontent.com/3516343/54081308-32c42d80-4346-11e9-9306-b5aef352c98b.png)

**Comment by eai04191** [comment]
レイアウトが変わるタイミングで画像のclassを`card-img-left`から`card-img-top`に付け替えればいいが、そのためにjsをつかうのもアレなので、2つの画像を入れておいて`d-`で切り替えるべき？

**Comment by shibafu528** [comment]
```scss
.card-img-top-to-left {
    width: 100%;
    @include media-breakpoint-down(md) {
        @include border-top-radius($card-inner-border-radius);
    }
    @include media-breakpoint-up(lg) {
        @include border-left-radius($card-inner-border-radius);
    }
}
```

みたいなの置けばいいんじゃないの、と思ったのですが邪道ですかね……
